### ISSUE TITLE
Version 1.0.4 is incompatible with Ruby 3.0.0

### ISSUE THREAD

**Issue by ElMonx** [rails/rails-controller-testing#69] opened 2021-05-06 02:33 UTC
Using Rails 6.1.3.1, Ruby 3.0.0 and rails-controller-testing 1.0.4, calling:

`post users_path, params: { user: { first_name: 'Test', last_name: 'Testington' } }`

or:

`patch user_path(@user), params: { user: { first_name: 'Test', last_name: 'Testington' } }`

causes the following error:

`ArgumentError: wrong number of arguments (given 2, expected 1)`

On 1.0.5 this doesn't happen anymore, I think since #58 was merged (adding **kwargs in the testing integration module).

Since it took me a while to track down the source of the problem and it could happen to somebody else, I think it would be useful to have this incompatibility noted somewhere in the Readme.

**Comment by gotoAndBliss** [comment] 2021-09-02 07:00
Noticed this too. Trying to work out a way to remove this lib from rspec now.

**Comment by SandyWang16** [comment] 2021-10-18 08:54
Hi, I Using Rails 6.1.4.1, Ruby 3.0.2 and rails-controller-testing version 1.0.5 

when calling 
`post url, { headers: { 'HTTP_REFERER': '123' } }` 
or 
`patch url, { params: { num: 20.0 } }` 

also occured `ArgumentError: wrong number of arguments (given 2, expected 1)`
https://github.com/rails/rails-controller-testing/pull/62  was merged, but not release in Version 1.0.5 

so i changed coding style:
`post url,   headers: { 'HTTP_REFERER': '123' } ` 
` patch url, params: { num: 20.0 }`

**Comment by jsantos** [comment] 2021-10-29 08:49
I still bump into this issue while trying to upgrade to Ruby 3.0... Even by referring to the repository on the Gemfile :(

Use case:

```ruby
get :section, params: params
```

where `params` is defined previously as `let(:params) { { section_id: section.id  } }`.

**Comment by rafaelfranca** [comment] 2021-11-02 02:38
We are using this gem with Ruby 3.1 even and we see no problem at all. Can you please provide a way to reproduce the issue?

**Comment by jsantos** [comment] 2021-11-24 12:48
@rafaelfranca I ended up figuring out that the issue was coming from another dependency (it was`apipie-rails` just in case someone is using this and doesn't figure out where the issue is from).

**Closed as completed** 2022-03-23 19:21 UTC
