### ISSUE TITLE
Rails 7 Support

### ISSUE THREAD

**Issue by caseyprovost** [rails/rails-controller-testing#75] opened 2022-03-23 16:51 UTC
On the latest commit I am seeing the following for rails 7:

```
Failure/Error: get :index, params: { company_id: company }

      ArgumentError:
        wrong number of arguments (given 2, expected 1)
```

The offending line seems to be: `rails-controller-testing-21014e48be12/lib/rails/controller/testing/integration.rb:13`

**Comment by rafaelfranca** [comment] 2022-03-23 19:20
Do you have the entire backtrace? How can I reproduce this error? We use this gem with Rails 7 and I don't see this error.

**Comment by rafaelfranca** [comment] 2022-03-23 19:20
Duplicate of #69

**Closed as completed by rafaelfranca** 2022-03-23 19:20 UTC

**Comment by caseyprovost** [comment] 2022-03-23 20:33
@rafaelfranca I tried to clean up the stacktrace to protect the company but let me take another pass and I'll see if I can't find a better representation.

For clarity do you also test using the syntax above? `get :index, params: { company_id: company }`

**Comment by caseyprovost** [comment] 2022-03-23 20:33
Oh it's a Ruby 3 issue, totally forgot to mention we are on Ruby 3

**Comment by rafaelfranca** [comment] 2022-03-23 21:11
Yes, exactly that. In #69 it seems the same problem was caused by a gem. The backtrace would be able to tell you that.
